version: '3'
services:
  web:
    build: .
    command: npx nodemon server.js
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
